### ISSUE TITLE
2.2.1 Section 1 - Introduction Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#100]
This section involves the following:
Introduction
Background Research
Product Quality Attributes

**Comment by personryan** [comment]
06/02/23: Introduction Completed


![Image](https://user-images.githubusercontent.com/90229655/218235133-a6e6ffe9-964b-441e-a381-2b0046841c0a.png)

**Comment by personryan** [comment]
08/02/23: Background Research Done


![Image](https://user-images.githubusercontent.com/90229655/218235162-c3b99533-d3f4-4d50-9f39-553c532625b9.png)

**Comment by personryan** [comment]
11/02/23: Product Quality Attributes Completed

**Comment by FS75** [comment]
Reviewed
