### ISSUE TITLE
2.2.2 Section 2- Team's Features & Requirements Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#101]
This sections encompasses the following:
User Features
Functional Requirements
Non-functional Requirements
Use Case Diagram
Use Case Decriptions

**Comment by personryan** [comment]
11/02/23: Functional & Non-Functional Requirements Completed

![Image](https://user-images.githubusercontent.com/90229655/218235285-b3f77bf1-49d4-4aff-81b8-016a7decb49d.png)

**Comment by FS75** [comment]
Reviewed
