### ISSUE TITLE
2.2.2.1 User Features Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#102]
5 User Features accepted by client

**Comment by personryan** [comment]
11/02/23: 5 User Features Completed

![Image](https://user-images.githubusercontent.com/90229655/218235373-fe4c586f-34e2-4bef-a0b8-d1adc5605197.png)

**Comment by FS75** [comment]
Reviewed
