### ISSUE TITLE
2.2.2.2 Use Case Diagram Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#103]
Creation of use cases based on user features

**Comment by personryan** [comment]
11/02/23: Use Case Diagram Completed


![Image](https://user-images.githubusercontent.com/90229655/218235463-012156c8-8399-4ea6-8f3b-7a4dc712bf32.png)

**Comment by FS75** [comment]
Reviewed
