### ISSUE TITLE
2.2.2.3 Use Case Descriptions Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#104]
The team shall provide Use Case Descriptions for every use case.

**Comment by personryan** [comment]
11/02/23: Completed UC1-15:

Snippet of UC-1:


![Image](https://user-images.githubusercontent.com/90229655/218235560-0ba779ef-3937-4b9e-a9f0-921934bed933.png)


Snippet of UC-15:


![Image](https://user-images.githubusercontent.com/90229655/218235574-0c405b7f-5cb8-4c32-9c33-80a878767baf.png)

**Comment by personryan** [comment]
11/02/23: All use case descriptions can be found in Appendix B and has been reviewed
