### ISSUE TITLE
2.2.4 Section 4- Software Design Evaluation Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#106]
This section talks about the software design evaluation used for the project.

**Comment by FS75** [comment]
09/02/23:

![Image](https://user-images.githubusercontent.com/93301912/218235201-28840823-3668-49fc-aa3f-07d898dab308.png)

![Image](https://user-images.githubusercontent.com/93301912/218235210-e31893ce-b13f-4ffe-aa6f-dc8e8c039393.png)
