### ISSUE TITLE
2.2.5 Section 5- Project Plan Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#107]

**Comment by FS75** [comment]
09/02/23: Project Plan Complete

Gantt Chart:
[ICT2106_AY2223_T2--D1_p2-2_Gantt_Chart.pdf](https://github.com/JustBrandonLim/ICT2106_P2_Project/files/10712410/ICT2106_AY2223_T2--D1_p2-2_Gantt_Chart.pdf)

WBS:
[ICT2106_AY2223_T2--D1_p2-2_WBS.pdf](https://github.com/JustBrandonLim/ICT2106_P2_Project/files/10712411/ICT2106_AY2223_T2--D1_p2-2_WBS.pdf)



Burndown Chart:
![Image](https://user-images.githubusercontent.com/93301912/218235295-11019f26-59f2-4d9a-950f-65938c3c5ff2.png)
