### ISSUE TITLE
2.2.6 Section 6 & - Conclusion, References Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#108]
Conclusion of report
References used for the report

**Comment by personryan** [comment]
11/02/23: Conclusion


![Image](https://user-images.githubusercontent.com/90229655/218235739-bdcc0e86-859a-4de5-a4d4-89d4708b58a7.png)

**Comment by FS75** [comment]
Reviewed
