### ISSUE TITLE
1.1.1	Module Level Diagram

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project#11]

**Comment by wangqixian15** [comment]
![Image](https://user-images.githubusercontent.com/73416707/218182785-24f1bb7c-3532-4ecf-9d7a-d28a30ece471.png)

**Comment by wangqixian15** [comment]
![Image](https://user-images.githubusercontent.com/73416707/218182971-94cff42c-aaa0-472f-af49-0ba3313956ec.png)

**Comment by wangqixian15** [comment]
Module Level Class Diagram and Component Diagram Completed
