### ISSUE TITLE
1.3 Entity Relationship Diagrams

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project#16]

**Comment by pangkaho14** [comment]
integrated:


![Image](https://user-images.githubusercontent.com/71180280/218192760-a8063347-8219-47e5-a9b9-2ed82f01a743.png)



team:


![Image](https://user-images.githubusercontent.com/71180280/218192830-ae852e02-3b5d-4fa8-946c-ef8a09c39f10.png)
