### ISSUE TITLE
D2 Retrospective Minutes

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project#181]
A retrospective was held and the following is what is discussed by the team on:

1. What did the team do well?
2. What didn't go well?
3. What can be improved?

The following are what was discussed during the retrospective using starfish retrospective. The starfish retrospective helps to identify and prioritize the areas of improvement by considering five key aspects: what to keep doing, what to stop doing, what to start doing, what to do less of, and what to do more of.

Each comment by a team member summarizes the key points that each member felt.

**Comment by fabianchua6** [comment]
Personal Reflection:

As the team lead, I feel satisfied with the team's performance and the successful implementation of features. I felt the importance of good software development practices and communication in achieving a seamless integration. However, I do recognize that there is room for improvement, such as incorporating more design patterns and exploring class-based approaches.


Starfish Format:
- Start Doing: Incorporate more design patterns and explore class-based approaches.
- Keep Doing: Overseeing work allocation, monitoring progress, ensuring good code practice, and facilitating clear communication between teams.
- More Of: Focusing on AGILE practices and promoting a healthy team environment.
- Less Of: Being overly cautious about the risk-reward ratio that might prevent the team from trying out new approaches.
- Stop Doing: Underestimating the potential benefits of integrating new approaches and technologies in the project.

**Comment by normanchia** [comment]
I have found implementing the decorator pattern to be a transformative experience, changing how I will approaches software design. In the future, I will try my best to prioritize using SOLID principles and appropriate design patterns in future projects, as I believes this will lead to improved software quality and efficiency. I am excited about applying this newfound knowledge and skills to future projects.

 • Start Doing: Prioritizing SOLID principles and selecting the most appropriate design patterns for the system components.
 • Keep Doing: Implementing the decorator pattern and following the Single Responsibility and Open-Closed principles.
 • More Of: Focusing on scalability, maintainability, and cost savings in software design.
 • Less Of: Limiting the use of design patterns based on preconceived notions.
 • Stop Doing: Choosing design patterns without considering their potential drawbacks and trade-offs.

**Comment by pangkaho14** [comment]
Personal Reflection:

I initially had reservations about using design patterns and SOLID principles due to their perceived complexity and additional overhead. However, after experiencing the benefits of these principles firsthand, I gain a deeper appreciation of design patterns in facilitating adaptability and maintainability. I learned the value of design patterns and SOLID principles in software development and I plan to incorporate them in my future projects.

Starfish Format:

 • Start Doing: Actively incorporating SOLID principles and design patterns in future projects.
 • Keep Doing: Communicating and establishing good relations with teammates and other teams to support developmental efforts.
 • More Of: Design first, code later. Being open to exploring new design principles and methodologies in software development.
 • Less Of: Being skeptical about new principles without trying them out and rushing headfirst into implementation.
 • Stop Doing: Prioritizing YAGNI principles over SOLID principles without considering the project's long-term requirements.

**Comment by wangqixian15** [comment]
Personal Reflection:

I've come to realize the significance of utilizing appropriate software architecture patterns and construction design approaches to ensure well-structured, maintainable, and scalable software. Through my experience, I have developed a deeper appreciation for adhering to SOLID principles and using activity diagrams to visualize feature implementation. Moving forward, I plan to continue applying these principles and practices to my future software development work.

Starfish Format:

 • Start Doing: Further exploring the use of construction design approaches to aid in feature implementation.
 • Keep Doing: Implementing the Device Control feature, adhering to SOLID principles, and using layer architecture patterns.
 • More Of: Utilizing activity diagrams to visualize feature flows and identify potential issues.
 • Less Of: Relying solely on class diagrams for feature implementation planning.
 • Stop Doing: Hesitating to explore new design patterns and methodologies that can improve the overall software development process.

**Comment by ShaunVSIT** [comment]
Personal Reflection:

I have come to realize the practical value of software development skills and the critical role that efficient software tools play. I have recognized the importance of investing time in understanding development tools and frameworks and applying SOLID principles and design patterns to develop more manageable and readable code. To enhance the overall quality of my code, I intend to devote more time to learning and applying design patterns and principles in future projects.

Starfish Format:

 • Start Doing: Investing more time in researching and understanding different design patterns and effectively applying them to projects.
 • Keep Doing: Implementing 2D interactive grids and working with ASP .NET framework and C# programming language.
 • More Of: Focusing on long-term implications of design decisions and using appropriate design patterns for different scenarios.
 • Less Of: Not dedicating enough time to learning new design patterns and principles.
 • Stop Doing: Prioritizing short-term solutions over long-term maintainability and extensibility in software design.
