### ISSUE TITLE
4.4 D2 Retrospection Start: 31/03/23 | End: 31/03/2023

### ISSUE THREAD

**Issue by FS75** [JustBrandonLim/ICT2106_P2_Project#182]
The team will conduct a retrospection and provide their sentiments about D2, along with what they have learnt and what they will do better for future projects.

**Comment by personryan** [comment]
31/03/2023:
I learnt how to apply design patterns and solid principles to my code. This helped to ensure the testability and maintainability of my code as it made it much more streamlined and cleaner. 

In future projects I would like to be more disciplined in updating the project items that I am responsible for. This would be acted on by ensuring that project items are continually updated based on when the item is being done.

**Comment by brucewzj99** [comment]
31/3

In D2, I gained valuable insights into design patterns and applying SOLID principles to my projects, which contributed to their scalability. Implementing Single Responsibility and Interface Segregation Principles in UF1 helped streamline workflow and make interfaces specific and adaptable. I finalized the account management feature on the web application side by optimizing React communication with the backend, adding functionalities such as changing passwords, and onboard device registration. This provided a more seamless and user-friendly experience, ensuring security and a smoother onboarding experience. Overall, this experience was fulfilling and helped me grow as a developer.

**Comment by DoubleBounce** [comment]
As we moved into D2, my focus shifted towards implementing specific features. One of my main tasks was to work on the shared profile and scenario feature, which involved developing the backend functionality for this feature. This was a complex task that required a deep understanding of the project's architecture and design. 

In addition to working on the shared profile and scenario feature, I also took on the task of improving our code's adherence to SOLID principles. Specifically, I implemented the Write and Read services for the Profile feature, which included creating interfaces and the service classes to implement them, which helped to ensure that our code adhered to the Single Responsibility Principle and Interface Segregation Principle.

My expertise in the project's architecture and design, combined with my ability to work collaboratively with the team, enabled us to overcome complex challenges and deliver high-quality code.

**Comment by FS75** [comment]
# 31/03/2023

Throughout D2, I successfully implemented 2FA for enhanced security, optimised React endpoint communication, adopted ISP for email service class, and implemented the builder pattern. These achievements improved system performance, modular design, and maintainability. This experience enhanced my technical skills and taught me valuable lessons in software development, such as security, efficient communication, SOLID principles, and design patterns. These skills prepare me for future projects that demand high-level technical expertise and adaptability, such as the smart home manager application.

**Comment by Lavenzaa** [comment]
31/03/2023

During my time on D2, I worked on the front-end development of the shared profile feature, designing and implementing a dynamic web page to display user profiles, scenarios, and rules. Additionally, I contributed to setting up back-end endpoints for scenarios and rules, gaining a deeper understanding of SOLID principles and their importance in writing cleaner and more maintainable code.

Through the project, I learned that adhering to SOLID principles and using design patterns, such as the factory pattern, can lead to more scalable and maintainable code. The project allowed me to gain practical experience working on a complex software project, and I was able to see firsthand the benefits of following SOLID principles and using design patterns. Overall, the skills and knowledge I acquired will be valuable for my future in software development.

**Comment by Lth323** [comment]
31/03/2023:

By applying the single responsibility principle to ensure clear and singular purpose for each class and segregating the interfaces to maintain clarity and flexibility of each class. I gained a deeper understanding of software architecture and its impact on the development process, and how it can greatly enhance scalability and flexibility.

What we could have improved on perhaps is to integrate to a certain extent to allow a more intuitive demo for the client.
