### ISSUE TITLE
2.2.1 Component Interface Classes

### ISSUE THREAD

**Issue by fabianchua6** [JustBrandonLim/ICT2106_P2_Project#30]

**Comment by pangkaho14** [comment]
Done

provided:


![Image](https://user-images.githubusercontent.com/71180280/218191314-b44bd614-8923-4998-8531-068979c554b9.png)


required:


![Image](https://user-images.githubusercontent.com/71180280/218191397-9cb49fc4-7b02-4d46-8dfc-260b404c2fce.png)
