### ISSUE TITLE
1.2 Team Class Diagram Start: 10/01/23 | End: 27/01/23

### ISSUE THREAD

**Issue by personryan** [JustBrandonLim/ICT2106_P2_Project#84]
Start: 10/01/23 | End: 27/01/23

- Creation of Team Class Diagram
- Linking of Class Diagram with other Teams

**Comment by personryan** [comment]
Team's Class Diagram dated 25/1/23:


![Image](https://user-images.githubusercontent.com/90229655/218231723-724e8e60-4aea-45c4-aa93-bad7e5758c20.png)

**Comment by personryan** [comment]
**Team's Class Diagram with communication to other teams 27/01/2023:**
example: Account Component -> Data Source Layer & Other Teams’ Services

![Image](https://user-images.githubusercontent.com/90229655/218231817-c84bd225-7bac-4b74-86d6-993fcd5969eb.png)

**Comment by FS75** [comment]
Reviewed
