### ISSUE TITLE
Start: 10/01/2023 | End: 10/01/2023 - Client Meeting Minutes

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#85]
Minutes for the client meeting dated 10/1/2023, 15:30

**Comment by brucewzj99** [comment]
[Client_Meeting_Minutes.docx](https://github.com/JustBrandonLim/ICT2106_P2_Project/files/10712311/Client_Meeting_Minutes.docx)

**Comment by FS75** [comment]
Reviewed
