### ISSUE TITLE
Start: 11/01/2023 | End: 13/01/2023 - List out requirements and features of application

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#86]
The team will:

    List out some requirements of the application
    Extract features from the requirements listed

**Comment by brucewzj99** [comment]
Requirements Listed Out:

    The system shall allow profiles to be password protected
    The system shall automatically configure devices according to the preset values configured by the developers.
    The system shall allow users to share the configurations of their devices with other users.

Features Extracted (from all existing requirements listed out in module 1's shared document):

    Users are able to edit all profile information, except for the profile ID.
    Users are able to individually manage smart devices in rooms
    Users are able to change device settings according to their preferences.
    Users are able to apply pre-existing settings to similar devices.
    Users are able to share the configurations of their devices with other users via a shared platform.
    Users are able to view the household usage logs of the system.

**Comment by FS75** [comment]
Reviewed
