### ISSUE TITLE
Start: 14/01/2023 | End: 14/01/2023 - Decide on features of application to work on

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#87]
The team will decide on what features of the application we will be working on for the rest of the project life cycle during Module 1's meeting dated 14/01/2023, 20:30.

**Comment by brucewzj99** [comment]
Users are able to manage a household account.
    Users are able to manage many different profile settings per household account.
    Users are able to edit all profile information, except for the profile ID.
    Users are able to share their profiles with other users via a shared platform.
    Users are able to set up parental controls for profiles.
    Users are able to enable 2FA for their login.

**Comment by FS75** [comment]
Reviewed
