### ISSUE TITLE
Class Diagram (interfaces only)Start: 20/01/2023 | End: 01/02/2023

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#88]
The team will create a class diagram including ONLY the interfaces that will be utilised in the system, based on the features that our team is working on

**Comment by brucewzj99** [comment]
20/1/2023: Tentative interfaces with methods (to be updated after evaluation in W4)

![Image](https://user-images.githubusercontent.com/24997286/218232609-9d437b43-c76b-4c5f-ac91-e569d5a72ed1.png)

**Comment by brucewzj99** [comment]
24/1/2023: Tentative interfaces with methods V2 (to be updated after evaluation in W4)

![Image](https://user-images.githubusercontent.com/24997286/218232627-45506870-26d6-4469-96cc-1c8b57e1d7f7.png)

**Comment by brucewzj99** [comment]
1/2/2023: Completed interface classes

Note: "Completed" refers to the interface classes providing the sufficient methods at the time of posting. In future, more methods might be added into the interfaces as we progress with possible client requirement changes or other teams needing our team to implement more methods.

IAccountService:

![Image](https://user-images.githubusercontent.com/24997286/218232649-4ccdebcf-4d75-4e34-b972-82f1b5f27eef.png)

IProfileService:

![Image](https://user-images.githubusercontent.com/24997286/218232661-65d5c109-11fb-4a7f-bc09-55ede3c99de4.png)

**Comment by FS75** [comment]
Reviewed
