### ISSUE TITLE
2.1 Ideation Prototype Start: 30/01/23 | End: 07/02/23

### ISSUE THREAD

**Issue by personryan** [JustBrandonLim/ICT2106_P2_Project#91]
Background research on existing smart home applications:
Xiaomi
Apple

**Comment by personryan** [comment]
User Interfaces of Xiaomi & Apple smart home apps:


![Image](https://user-images.githubusercontent.com/90229655/218233957-4c176657-b813-4307-b9f0-eefa07f7c53f.png)

**Comment by personryan** [comment]
Functional features derived from research:

1. functional features that our application would have:
2. Add people/profiles to a household
3. Add devices to household/profiles
4. Control smart devices through the applications
5. Add scenarios that group multiple automation commands
6. Real time information on status of devices
7. Discover new smart home devices

**Comment by FS75** [comment]
Reviewed
