### ISSUE TITLE
1.3 Entity Relationship Diagram Start: 25/01/23 | End: 27/01/23

### ISSUE THREAD

**Issue by personryan** [JustBrandonLim/ICT2106_P2_Project#93]
Entity relationship diagram of Account and Profile
Entity relationship diagram after integration

**Comment by personryan** [comment]
25/01/23: Entity Relationship Diagram of Account and Profile

![Image](https://user-images.githubusercontent.com/90229655/218233276-6ce96762-e0e6-4037-b235-3d7b56e1bc83.png)

**Comment by personryan** [comment]
27/01/23: Entity relationship diagram after integration


![Image](https://user-images.githubusercontent.com/90229655/218233361-cb63ca1b-ef5f-493e-9dc1-997cebc2faee.png)

**Comment by FS75** [comment]
27/01/23: Consolidated Entity Relationship Diagram

![Image](https://user-images.githubusercontent.com/93301912/218235158-3b4b0890-0b29-4405-a5df-d403cbed0195.png)
