### ISSUE TITLE
2.1.2.3 Email Service Start: 30/01/23 | End: 07/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#96]
After signing up, an email will be sent to notify user of the successful creation

**Comment by personryan** [comment]
07/02/2023: Email Service Code Snippet


![Image](https://user-images.githubusercontent.com/90229655/218234442-2000aeca-e6c9-4861-b7f6-25792283e69a.png)

**Comment by personryan** [comment]
07/02/23: Reviewed
