### ISSUE TITLE
2.1.2.4 Account Repository & Account Seed Data for DB Start: 30/01/23 | End: 07/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#97]
Account Repository: Using unit of work to communicate with the SQLite DB
Account Seed Data: Creation of first object in table

**Comment by personryan** [comment]
07/02/23: Account Repository: code snippet


![Image](https://user-images.githubusercontent.com/90229655/218234538-1e6277a9-1045-46ce-87df-5732f1d20dca.png)

**Comment by personryan** [comment]
07/02/23: Account Seed Data: code snippet


![Image](https://user-images.githubusercontent.com/90229655/218234565-062dc8c3-dcd5-4d9d-84d9-cf41de03035b.png)

**Comment by personryan** [comment]
07/02/23: Nothing to be added and reviewed.
