### ISSUE TITLE
2.1.3 Client Demo 1 Start: 30/01/23 | End: 07/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#98]
Client Demo for the following:
One completed feature:  Users are able to register, login, and manage a household account.

 Prototype: Users are able to add profiles to an account, edit all profile information (except profile ID), and manage them.

**Comment by personryan** [comment]
Completed Feature: User Registartion


![Image](https://user-images.githubusercontent.com/90229655/218234832-6b14b738-674d-46c9-9650-74454c4b3df3.png)

**Comment by personryan** [comment]
Prototype: Profile Pages


![Image](https://user-images.githubusercontent.com/90229655/218234876-445febbe-125d-4e85-abc0-f385cf201367.png)



![Image](https://user-images.githubusercontent.com/90229655/218234884-9843da97-23aa-45f6-ae0f-8ed029b09c8c.png)

**Comment by FS75** [comment]
Reviewed
