### ISSUE TITLE
2.2 Initial Design Document Start: 06/02/23 | End: 11/02/23

### ISSUE THREAD

**Issue by brucewzj99** [JustBrandonLim/ICT2106_P2_Project#99]
The team shall provide an initial design document that covers the system's design.

**Comment by personryan** [comment]
11/02/23: Settled on the design of document


![Image](https://user-images.githubusercontent.com/90229655/218235077-ca53b55e-b66a-402d-8df5-603bab113e51.png)



![Image](https://user-images.githubusercontent.com/90229655/218235083-86c965f1-d99d-4257-b64b-c12358eb932e.png)

**Comment by FS75** [comment]
Reviewed all sections
